/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tesTree.java
 *
 * Created on 2012/03/16, 23:22:02
 */
package my.utilities.db.gui;
import my.constants.*;
//import my.db.classes.common.*;
//import my.db.classes.core.*;
//import my.db.gui.tree.treenode.*;
import javax.swing.tree.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author noriyuki
 */
public class tesTreeWithModel extends javax.swing.JFrame implements javax.swing.event.TreeSelectionListener{

    //private JTree tree;

    
    /** Creates new form tesTree */
    public tesTreeWithModel() {
        
        my.db.classes.common.ParaSQLServerMS para=new my.db.classes.common.ParaSQLServerMS();
        para.setForNameString(my.db.constants.ConstantsDB.MS_SQLSERVER_FOR_NAME_STRING);
        para.setNamDataBase("tes_haid");
        para.setNameHost("192.168.0.4");
        para.setNameProduct(my.db.constants.ConstantsDB.MS_SQLSERVER_PRODUCT_NAME);
        para.setNameServerInstance("sqlexpress");
        para.setPassWord("Noriyuki");
        para.setPort(my.db.constants.ConstantsDB.MS_SQLSERVER_PORT);
        para.setUser("noriyuki");
        
        initComponents();
        JTree tree=my.db.utilities.UtilitiesGUI.createTreeOfDatabase(para);
        tree.addTreeSelectionListener(this);
        this.pane_table.setViewportView(tree);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        tabbed_pane = new javax.swing.JTabbedPane();
        pane_table = new javax.swing.JScrollPane();
        btnEnd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane.setName("pane"); // NOI18N

        tabbed_pane.setName("tabbed_pane"); // NOI18N

        pane_table.setName("pane_table"); // NOI18N
        tabbed_pane.addTab("tables", pane_table);

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tabbed_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(tabbed_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnEnd.setText("E N D");
        btnEnd.setName("btnEnd"); // NOI18N
        btnEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEndMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnd)
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEndMouseClicked
        // TODO add your handling code here:
        this.common_btnEndClicked();
    }//GEN-LAST:event_btnEndMouseClicked
    private void common_btnEndClicked(){
        this.setVisible(false);
        System.exit(Constants.CS_SYSTEM_EXIT_OK);
    }
    private JTree createTree(my.db.classes.common.ParaSQLServerMS para){
        
        //ParaSQLServerMS para=new ParaSQLServerMS();
        
        my.db.classes.core.Database db=new my.db.classes.core.Database(para);
        
        //db=my.db.utilities.Utilities.getPropertiesOfDB(para);        
        //System.out.println("num tables is " +db.getNumOfTables());        
        DefaultMutableTreeNode nodeDB=new DefaultMutableTreeNode(db);
        
        //tables begin
        for(int i_tables=Constants.CS_ZERO_AS_INT;i_tables<db.getNumOfTables();i_tables++){

            DefaultMutableTreeNode nodeTable=new DefaultMutableTreeNode(db.getTable(i_tables));
            //fields begin
            for(int i_fields=Constants.CS_ZERO_AS_INT;i_fields<db.getTable(i_tables).getNumOfFields();i_fields++){

                my.db.gui.tree.treenodes_old.Field nodeField=new my.db.gui.tree.treenodes_old.Field(db.getTable(i_tables).getField(i_fields));
                nodeTable.add((javax.swing.tree.DefaultMutableTreeNode)nodeField);
            }
            //fields end
            nodeDB.add(nodeTable);            
        }

        //tables end
        
        //finally
        DefaultTreeModel model=new DefaultTreeModel(nodeDB);
        
        return new JTree(model);
        
    }
    //tree selection listener
    public void valueChanged(javax.swing.event.TreeSelectionEvent e){
        
        javax.swing.tree.TreePath a_treepath=e.getNewLeadSelectionPath();
        javax.swing.tree.DefaultMutableTreeNode a_node;
        Object an_object;
        String obj_type="";
        
        System.out.println("");       
        System.out.println(new java.util.Date().toString());
        
        a_node=(javax.swing.tree.DefaultMutableTreeNode)a_treepath.getLastPathComponent();
        an_object=a_node.getUserObject();
        if(a_node.getUserObject() instanceof my.db.classes.core.Database){
            obj_type="database";
        }
        if(an_object instanceof my.db.classes.core.Table){
            obj_type="table";
        }
        if(an_object instanceof my.db.classes.core.Field){
            obj_type="field";
        }
        if(an_object instanceof my.db.classes.core.FieldLength){
            obj_type=a_node.getParent()+ " length";           
        }
        if(an_object instanceof my.db.classes.core.FieldType){
            obj_type=a_node.getParent()+" type";
        }
        System.out.println("select "+obj_type);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tesTreeWithModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tesTreeWithModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tesTreeWithModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tesTreeWithModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tesTreeWithModel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JPanel pane;
    private javax.swing.JScrollPane pane_table;
    private javax.swing.JTabbedPane tabbed_pane;
    // End of variables declaration//GEN-END:variables
}
