/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerChooserGUI.java
 *
 * Created on 2011/12/11, 4:22:01
 */
package my.utilities.db.server_selector;
import my.db.constants.ConstantsDB;
import my.constants.*;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author noriyuki
 */
public class ServerChooserGUI extends javax.swing.JDialog {

    private my.db.classes.common.ParaSQLServer para=new my.db.classes.common.ParaSQLServer();
    private my.db.classes.common.ParaSQLServerMS para_ms=new my.db.classes.common.ParaSQLServerMS();
    
    Object rv;
    
    /** Creates new form ServerChooserGUI */
    public ServerChooserGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_host = new javax.swing.JTextField();
        txt_server_instance = new javax.swing.JTextField();
        txt_database_name = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        txt_user_name = new javax.swing.JTextField();
        txt_for_name_string = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        lbl_host = new javax.swing.JLabel();
        lbl_server = new javax.swing.JLabel();
        lbl_database = new javax.swing.JLabel();
        lbl_product = new javax.swing.JLabel();
        lbl_port = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_pass_word = new javax.swing.JLabel();
        lbl_for_name_string = new javax.swing.JLabel();
        btn_connect = new javax.swing.JButton();
        txt_pass_word = new javax.swing.JPasswordField();
        cmbbx_product_name = new javax.swing.JComboBox();
        btn_clear_all = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("choose data base server");
        setName("dlg_main"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txt_host.setName("txt_host"); // NOI18N

        txt_server_instance.setName("txt_server_instance"); // NOI18N

        txt_database_name.setName("txt_database_name"); // NOI18N

        txt_port.setName("txt_port"); // NOI18N

        txt_user_name.setName("txt_user_name"); // NOI18N

        txt_for_name_string.setName("txt_for_name_string"); // NOI18N

        btn_cancel.setText("cancel");
        btn_cancel.setName("btn_cancel"); // NOI18N
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });
        btn_cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_cancelKeyPressed(evt);
            }
        });

        btn_ok.setText("ok");
        btn_ok.setName("btn_ok"); // NOI18N
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
        });
        btn_ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_okKeyPressed(evt);
            }
        });

        lbl_host.setText("host name or ip address:");
        lbl_host.setName("lbl_host"); // NOI18N

        lbl_server.setText("server instance name:");
        lbl_server.setName("lbl_server"); // NOI18N

        lbl_database.setText("database name:");
        lbl_database.setName("lbl_database"); // NOI18N

        lbl_product.setText("product name:");
        lbl_product.setName("lbl_product"); // NOI18N

        lbl_port.setText("port number:");
        lbl_port.setName("lbl_port"); // NOI18N

        lbl_user.setText("user name:");
        lbl_user.setName("lbl_user"); // NOI18N

        lbl_pass_word.setText("pass word:");
        lbl_pass_word.setName("lbl_pass_word"); // NOI18N

        lbl_for_name_string.setText("for name strng:");
        lbl_for_name_string.setName("lbl_for_name_string"); // NOI18N

        btn_connect.setText("test connect");
        btn_connect.setName("btn_connect"); // NOI18N
        btn_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_connectMouseClicked(evt);
            }
        });
        btn_connect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_connectKeyPressed(evt);
            }
        });

        txt_pass_word.setName("txt_pass_word"); // NOI18N

        cmbbx_product_name.setName("cmbbx_product_name"); // NOI18N
        cmbbx_product_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbx_product_nameItemStateChanged(evt);
            }
        });

        btn_clear_all.setText("clear all");
        btn_clear_all.setName("btn_clear_all"); // NOI18N
        btn_clear_all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clear_allMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_host)
                    .addComponent(lbl_database)
                    .addComponent(lbl_port)
                    .addComponent(lbl_user)
                    .addComponent(lbl_for_name_string)
                    .addComponent(lbl_pass_word)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_connect)
                        .addComponent(lbl_server))
                    .addComponent(lbl_product))
                .addGap(35, 35, 35)
                .addComponent(btn_clear_all)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_pass_word, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txt_for_name_string, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txt_user_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txt_port, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txt_database_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txt_server_instance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txt_host, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbbx_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_host)
                    .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_server)
                    .addComponent(txt_server_instance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_database)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_database_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbbx_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_port)
                            .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_user)
                            .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_product))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pass_word)
                    .addComponent(txt_pass_word, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_for_name_string)
                    .addComponent(txt_for_name_string, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_connect)
                    .addComponent(btn_cancel)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear_all))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_okKeyPressed
        // TODO add your handling code here:
        this.common_action_btn_ok();
    }//GEN-LAST:event_btn_okKeyPressed

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        // TODO add your handling code here:
        this.common_action_btn_ok();        
    }//GEN-LAST:event_btn_okMouseClicked

    private void btn_connectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_connectKeyPressed
        // TODO add your handling code here:
        this.common_action_btn_connect();        
    }//GEN-LAST:event_btn_connectKeyPressed

    private void btn_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_connectMouseClicked
        // TODO add your handling code here:
        this.common_action_btn_connect();
    }//GEN-LAST:event_btn_connectMouseClicked

    private void btn_cancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_cancelKeyPressed
        // TODO add your handling code here:
        this.common_action_btn_cancel();
    }//GEN-LAST:event_btn_cancelKeyPressed

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        // TODO add your handling code here:
        this.common_action_btn_cancel();
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void cmbbx_product_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbx_product_nameItemStateChanged
        // TODO add your handling code here:
        this.common_action_cmbx_product_name_selected();
    }//GEN-LAST:event_cmbbx_product_nameItemStateChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.common_action_form_component_shown();
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.txt_host.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btn_clear_allMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clear_allMouseClicked
        // TODO add your handling code here:
        this.common_action_btn_clear_all();
    }//GEN-LAST:event_btn_clear_allMouseClicked
    private void common_action_form_component_shown(){
        
        //set product names
        this.cmbbx_product_name.removeAllItems();
        this.cmbbx_product_name.addItem(ConstantsDB.MS_SQLSERVER_PRODUCT_NAME);
        this.cmbbx_product_name.addItem(ConstantsDB.MySQL_PRODUCT_NAME);        
    }
    private void common_action_cmbx_product_name_selected(){
        
        String product_name;
        String buff;
        
        buff=(String)this.cmbbx_product_name.getSelectedItem();        
        product_name=buff.toLowerCase();
        
        if(product_name.equals(ConstantsDB.MS_SQLSERVER_PRODUCT_NAME)){
            this.txt_port.setText(ConstantsDB.MS_SQLSERVER_PORT);
            this.txt_for_name_string.setText(ConstantsDB.MS_SQLSERVER_FOR_NAME_STRING);
        }
        if(product_name.equals(ConstantsDB.MySQL_PRODUCT_NAME)){
            this.txt_port.setText(ConstantsDB.MySQL_PORT);
            this.txt_for_name_string.setText(ConstantsDB.MySQL_FOR_NAME_STRING);
        }
        if((product_name.equals(ConstantsDB.MS_SQLSERVER_PRODUCT_NAME)||(product_name.equals(ConstantsDB.MySQL_PRODUCT_NAME)))){
            this.txt_user_name.requestFocus();
        }
        
    }
    /*
    private void common_action_btn_end(){
        
        this.common_action_btn_ok();
        this.setVisible(false);
        
    }
     * 
     */
    private void common_action_btn_clear_all(){
        this.txt_database_name.setText(Constants.CS_SPACE);
        this.txt_for_name_string.setText(Constants.CS_SPACE);
        this.txt_host.setText(Constants.CS_SPACE);
        this.txt_pass_word.setText(Constants.CS_SPACE);
        this.txt_port.setText(Constants.CS_SPACE);
        //this.txt_product_name.setText(my.constants.ConstantsDB.CS_SPACE);
        this.cmbbx_product_name.setSelectedIndex(Constants.CS_LIST_INDEX_INIT);     
        this.txt_server_instance.setText(Constants.CS_SPACE);
        this.txt_user_name.setText(Constants.CS_SPACE);        
    }
    private void common_action_btn_ok(){
        this.setParaFromForm();
        this.setVisible(false);
    }
    private void setParaFromForm(){
        
        String product_name;
        String buff;
        
        buff=(String)this.cmbbx_product_name.getSelectedItem();        
        product_name=buff.toLowerCase(); 
        //
        this.para.setForNameString(this.txt_for_name_string.getText());
        this.para.setNamDataBase(this.txt_database_name.getText());       
        this.para.setNameHost(this.txt_host.getText());
        this.para.setNameProduct((String)this.cmbbx_product_name.getSelectedItem());        
        this.para.setNameServerInstance(this.txt_server_instance.getText());
        this.para.setPassWord(this.txt_pass_word.getText());
        this.para.setPort(this.txt_port.getText());
        this.para.setUser(this.txt_user_name.getText());
        //
        this.para_ms.setForNameString(this.txt_for_name_string.getText());
        this.para_ms.setNamDataBase(this.txt_database_name.getText());       
        this.para_ms.setNameHost(this.txt_host.getText());
        this.para_ms.setNameProduct((String)this.cmbbx_product_name.getSelectedItem());        
        this.para_ms.setNameServerInstance(this.txt_server_instance.getText());
        this.para_ms.setPassWord(this.txt_pass_word.getText());
        this.para_ms.setPort(this.txt_port.getText());
        this.para_ms.setUser(this.txt_user_name.getText());
        
        //
        if(product_name.equals(ConstantsDB.MS_SQLSERVER_PRODUCT_NAME)){
            this.rv=this.para_ms;
        }
        if(product_name.equals(ConstantsDB.MySQL_PRODUCT_NAME)){
            this.rv=this.para;
        }
                
    }
    private void common_action_btn_connect(){
     
        String message;
        JLabel label=new JLabel();
        
        //this.common_action_btn_ok();
        this.setParaFromForm();
        if(my.db.utilities.Utilities.isEnableServer(rv)){
            //when success
            label.setText("connecting db server is OK.");
            label.setForeground(Color.BLACK);
        }else{
            //when failed
            label.setText("connecting db server is NG.");             
            label.setForeground(Color.RED);
        }
        
        JOptionPane.showMessageDialog(this, label);
        
    }
    private void common_action_btn_cancel(){
        rv=null;
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ServerChooserGUI dialog = new ServerChooserGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear_all;
    private javax.swing.JButton btn_connect;
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox cmbbx_product_name;
    private javax.swing.JLabel lbl_database;
    private javax.swing.JLabel lbl_for_name_string;
    private javax.swing.JLabel lbl_host;
    private javax.swing.JLabel lbl_pass_word;
    private javax.swing.JLabel lbl_port;
    private javax.swing.JLabel lbl_product;
    private javax.swing.JLabel lbl_server;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt_database_name;
    private javax.swing.JTextField txt_for_name_string;
    private javax.swing.JTextField txt_host;
    private javax.swing.JPasswordField txt_pass_word;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_server_instance;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
}
